services:
  backend:
    build: ./backend
    container_name: sintonia_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persistencia: Montamos la DB local dentro del contenedor
      - ./backend/backend.db:/app/backend.db
    environment:
      - DATABASE_URL=sqlite://backend.db
      - HOST=0.0.0.0

  frontend:
    build: ./frontend
    container_name: sintonia_frontend
    restart: unless-stopped
    ports:
      - "4321:80"
    depends_on:
      - backend